evidence(c1).
evidence(thickVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(thickVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(cloudsNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(cloudsNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(cloudsNDVI).
------
evidence(c1).
evidence(cloudsNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(cloudsNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(thickVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(thickVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(cloudsNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(cloudsNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(thickVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(cloudsNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(iceAndSnowNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(cloudsNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(scarceVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(thickVegetationNDVI).
------
evidence(c1).
evidence(cloudsNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(mediumVegetationNDVI).
------
evidence(c1).
evidence(waterNDVI).
------
evidence(c1).
evidence(bareGroundNDVI).
------
evidence(c2).
evidence(iceAndSnowNDVI).
------
evidence(c2).
evidence(mediumVegetationNDVI).
------
evidence(c2).
evidence(cloudsNDVI).
------
evidence(c2).
evidence(bareGroundNDVI).
------
evidence(c2).
evidence(mediumVegetationNDVI).
------
evidence(c2).
evidence(mediumVegetationNDVI).
------
evidence(c2).
evidence(mediumVegetationNDVI).
------
evidence(c2).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(iceAndSnowNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(iceAndSnowNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(thickVegetationNDVI).
------
evidence(c3).
evidence(iceAndSnowNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(iceAndSnowNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(thickVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(iceAndSnowNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(thickVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(iceAndSnowNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(bareGroundNDVI).
------
evidence(c3).
evidence(scarceVegetationNDVI).
------
evidence(c3).
evidence(waterNDVI).
------
evidence(c3).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(iceAndSnowNDVI).
------
evidence(c4).
evidence(bareGroundNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(waterNDVI).
------
evidence(c4).
evidence(bareGroundNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(bareGroundNDVI).
------
evidence(c4).
evidence(bareGroundNDVI).
------
evidence(c4).
evidence(iceAndSnowNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(waterNDVI).
------
evidence(c4).
evidence(waterNDVI).
------
evidence(c4).
evidence(cloudsNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(bareGroundNDVI).
------
evidence(c4).
evidence(iceAndSnowNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(waterNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(waterNDVI).
------
evidence(c4).
evidence(iceAndSnowNDVI).
------
evidence(c4).
evidence(scarceVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(waterNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(scarceVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(scarceVegetationNDVI).
------
evidence(c4).
evidence(bareGroundNDVI).
------
evidence(c4).
evidence(scarceVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(iceAndSnowNDVI).
------
evidence(c4).
evidence(iceAndSnowNDVI).
------
evidence(c4).
evidence(waterNDVI).
------
evidence(c4).
evidence(waterNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(cloudsNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(thickVegetationNDVI).
------
evidence(c4).
evidence(bareGroundNDVI).
------
evidence(c4).
evidence(waterNDVI).
------
evidence(c4).
evidence(thickVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(iceAndSnowNDVI).
------
evidence(c4).
evidence(cloudsNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c4).
evidence(bareGroundNDVI).
------
evidence(c4).
evidence(scarceVegetationNDVI).
------
evidence(c4).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(iceAndSnowNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(iceAndSnowNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(iceAndSnowNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(iceAndSnowNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(iceAndSnowNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(cloudsNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(iceAndSnowNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(scarceVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(bareGroundNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(iceAndSnowNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(waterNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(mediumVegetationNDVI).
------
evidence(c5).
evidence(thickVegetationNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(mediumVegetationNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(bareGroundNDVI).
------
evidence(c6).
evidence(waterNDVI).
------
evidence(c6).
evidence(waterNDVI).
